### ISSUE TITLE
notiziemusicali.it

### ISSUE THREAD

**Issue by JobcenterTycoon** [easylist/easylistitaly#15]
Ad on `https://notiziemusicali.it/`

<img width="1135" alt="Unbenannt" src="https://user-images.githubusercontent.com/48647394/161088034-fa5a30a9-db54-4216-9a01-cff6bdc0acf4.PNG">

Adblock: uBlock Origin default with EasyList, EasyPrivacy and EasyList Italy

**Comment by Khrin** [comment]
That's self-promotion
