### ISSUE TITLE
farmacia-aperta.eu

### ISSUE THREAD

**Issue by asder216** [easylist/easylistitaly#19]
Ciao :) c'è un grande banner su questo sito che riesco a nascondere con `www.farmacia-aperta.eu###adv-info`

Con ad:
![ConAd](https://user-images.githubusercontent.com/62883417/164268585-c32757a1-2919-4e1b-9507-0273592f1044.png)

Senza ad: 
![SenzaAd](https://user-images.githubusercontent.com/62883417/164268614-45e6ef9a-cc22-4f82-9816-ac74879aef1c.png)

**Comment by Khrin** [comment]
Grazie mille, aggiunto a EasyList Italy
