### ISSUE TITLE
[GEDI group] repubblica.it

### ISSUE THREAD

**Issue by Bertaz** [easylist/easylistitaly#24]
_English below_
Tutti i siti del GEDI group hanno aggiunto un cookiewall.
Esempio: `https://www.repubblica.it/tecnologia/blog/cyber-law/2022/10/19/news/vaccino_per_i_gay_e_dati_supersensibili_quando_la_privacy_puo_combattere_lo_stigma-370709925/`
Screenshot: ![image](https://user-images.githubusercontent.com/44445647/198162354-eaae9a1f-e4ac-46fc-bffb-4732d5b46f23.png)
Se l'utente non ha mai premuto "rifiuta e abbonati" sul banner `repubblica.it###iubenda-cs-banner` lo rimuove.
Se è stato premuto rifiuta, il sito setta 3 cookie: `_iub_cs-23960187-granular`, `_iub_cs-23960187` e `euconsent-v2` e appare un nuovo cookiewall (visivamente identico) che con `repubblica.it##.cookiewall` viene nascosto.
Altrimenti bloccare `cdn.iubenda.com/cs/iubenda_cs.js` li blocca in entrambi i casi.

Lista siti: `https://www.gedi.it/it/attivita/news`
<details>
 <summary>Composta da:</summary>

- `https://www.repubblica.it/`
- `https://www.lastampa.it/`
- `https://www.ilsecoloxix.it/`
- `https://www.huffingtonpost.it/`
- `https://gazzettadimantova.gelocal.it/mantova`
- `https://corrierealpi.gelocal.it/belluno`
- `https://nuovavenezia.gelocal.it/venezia`
- `https://laprovinciapavese.gelocal.it/pavia`
- `https://tribunatreviso.gelocal.it/treviso`
- `https://messaggeroveneto.gelocal.it/udine`
- `https://lasentinella.gelocal.it/ivrea`
- `https://ilpiccolo.gelocal.it/trieste`
- `https://mattinopadova.gelocal.it/padova`
</details>

Personalmente userei `||cdn.iubenda.com^*/iubenda_cs.js$script,3p`.
Se invece questa lista preferisce filtri cosmetici `repubblica.it,lastampa.it,ilsecoloxix.it,huffingtonpost.it,gelocal.it###iubenda-cs-banner` e `repubblica.it,lastampa.it,ilsecoloxix.it,huffingtonpost.it,gelocal.it##.cookiewall`.

---

_English_
All GEDI group's sites added a cookiewall.
Example: `https://www.repubblica.it/tecnologia/blog/cyber-law/2022/10/19/news/vaccino_per_i_gay_e_dati_supersensibili_quando_la_privacy_puo_combattere_lo_stigma-370709925/`
Screenshot: _see above_
If the user never clicked on "rifiuta e abbonati" in the banner `repubblica.it###iubenda-cs-banner` hides it.
Instead, if refuse was pressed, the site sets 3 cookies: `_iub_cs-23960187-granular`, `_iub_cs-23960187` and `euconsent-v2` and a new cookiewall (visually identical) appears, which can be hid by `repubblica.it##.cookiewall`.
Otherwise blocking `cdn.iubenda.com/cs/iubenda_cs.js` blocks the banner in both cases.

Sites list: `https://www.gedi.it/it/attivita/news`
<details>
 <summary>Composed of:</summary>

- `https://www.repubblica.it/`
- `https://www.lastampa.it/`
- `https://www.ilsecoloxix.it/`
- `https://www.huffingtonpost.it/`
- `https://gazzettadimantova.gelocal.it/mantova`
- `https://corrierealpi.gelocal.it/belluno`
- `https://nuovavenezia.gelocal.it/venezia`
- `https://laprovinciapavese.gelocal.it/pavia`
- `https://tribunatreviso.gelocal.it/treviso`
- `https://messaggeroveneto.gelocal.it/udine`
- `https://lasentinella.gelocal.it/ivrea`
- `https://ilpiccolo.gelocal.it/trieste`
- `https://mattinopadova.gelocal.it/padova`
</details>

I suggest `||cdn.iubenda.com^*/iubenda_cs.js$script,3p`.
Otherwise if cosmetic filters are preferred `repubblica.it,lastampa.it,ilsecoloxix.it,huffingtonpost.it,gelocal.it###iubenda-cs-banner` and `repubblica.it,lastampa.it,ilsecoloxix.it,huffingtonpost.it,gelocal.it##.cookiewall`.

**Comment by Khrin** [comment]
Ciao,
Chiudo qui perché questa lista serve solo per bloccare le pubblicità e questo non è il caso direi. Gli avvisi per i cookies sono in un'altra lista (https://github.com/easylist/easylist/tree/master/easylist_cookie) dove sono già presenti i filtri per `iubenda.com`. (Alcuni andrebbero rivisti, compresi quelli per `repubblica.it`, magari quando mi sarà possibile)

**Comment by Bertaz** [comment]
Ciao Khrin,
non avevo notato che le liste localizzate sono solo per le pubblicità e effettivamente in **easylist_cookie** sono già presenti sia `||iubenda.com^$third-party` che `/iubenda_cs.`
