### ISSUE TITLE
Empy AD spaces not hidden

### ISSUE THREAD

**Issue by gl-Hub** [easylist/easylistitaly#34]
Hi, I'm using uBlock Origin on Firefox for Android (version 10 in my case) and I’ve noticed that advertisements are blocked, but the relative empty spaces are not hidden as they are with the same sites using Firefox desktop.

I encountered the problem with these two sites:
**corriere.it**
**laleggepertutti.it** 

The option _“Hide placeholders of blocked elements”_ is enabled.

A few more details[ in this post](https://www.reddit.com/r/uBlockOrigin/comments/162lcgl/empy_ad_spaces_not_hidden/) on the Reddit page supporting uBlock Origin.

Thank you.

**Comment by Khrin** [comment]
Aggiorna le liste dei filtri.

**Comment by gl-Hub** [comment]
Ciao e grazie del pronto intervento !

Sul sito **Corriere.it** il problema è ora risolto, mentre sul sito **Laleggepertutti.it** è rimasto invariato.

**Comment by gl-Hub** [comment]
@Khrin

Sul sito **Laleggepertutti.it** le modifiche alla lista non hanno avuto alcun effetto e continuano a vedersi gi spazi relativi agli annunci pubblicitari bloccati.

Può dipendere da me o c'è un problema da qualche altra parte ?

**Comment by Khrin** [comment]
@gl-Hub Puoi postare uno screenshot della parte non bloccata, per cortesia?

**Comment by gl-Hub** [comment]
@Khrin 

Posto gli screenshot degli elementi incriminati evidenziati con l’ausilio dello strumento _“Seleziona elemento”_ dello stesso uBlock Origin, con cui sono riuscito a creare dei filtri locali per bloccarli.

Nell’ordine sono:

- [Banner in home page](https://i.imgur.com/i6gynpX.png)
- [Banner a fondo schermo in home page](https://i.imgur.com/tmuPMSJ.png)
- [Banner dell’articolo](https://i.imgur.com/A6eOZm2.png) ([necessarie una seconda regola](https://i.imgur.com/F9mw1VY.png))
- [Banner a fondo schermo dell’articolo](https://i.imgur.com/OiFxu4U.png)

**Comment by Khrin** [comment]
Spero che l'ultimo filtro aggiunto possa risolvere il problema...
