### ISSUE TITLE
[whitelist] oasjs.kataweb.it

### ISSUE THREAD

**Issue by scafroglia93** [easylist/easylistitaly#4]
this domain is used by one of the most important Italian newspapers for the use of the videos on their site

Main site ->
https://www.repubblica.it/

**Comment by Khrin** [comment]
Ciao Lorenzo,

Tu hai problemi ad riprodurre i video? Alcuni script di questo dominio sono già permessi da Easylist Italy https://github.com/easylist/easylistitaly/blob/master/easylistitaly/easylistitaly_allowlist.txt#L36 e non ho avuto problemi ad aprire, per esempio, il video qui `https://video.repubblica.it/tecno-e-scienze/amazon-l-esilarante-aneddoto-di-bezos-su-uno-dei-primi-ordini-ricevuti-nel-1995-dalla-bulgaria/375721/376335`

**Comment by scafroglia93** [comment]
NextDNS segnala che il dominio viene bloccato da easylist italy ->

https://easylist-downloads.adblockplus.org/easylistitaly.txt

é presente all'interno della lista

Il giorno gio 4 feb 2021 alle ore 12:15 Khrin <notifications@github.com> ha
scritto:

**Comment by Khrin** [comment]
Mi dispiace, ma purtroppo non posso fare molto in questo caso. Il funzionamento di Nextdns è particolare e io non posso aggiungere filtri per risolvere questo tuo problema.

Ti suggerisco di contattare direttamente Nextdns e provare ad esporgli il tuo problema, forse loro possono trovare una soluzione.

**Comment by superlex** [comment]
Hi @Khrin ,
please check 
https://github.com/AdguardTeam/AdguardFilters/issues/161801
Currently EasyList Italy blocks `oasjs.kataweb.it` and iubenda scripts aren't loaded.

**Comment by Khrin** [comment]
Thank you @superlex , I have removed the filter: https://github.com/easylist/easylistitaly/commit/0aef07c27300b87f1352232359c77a8f767f8e78

**Comment by superlex** [comment]
Thank to you, @Khrin :)
